

SELECT *
  FROM GNomEx.dbo.RequestCategory rc 
  JOIN GNomEx.dbo.ColumnProperties cp ON cp.codeRequestCategory = rc.codeRequestCategory





INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory
                                        , gridType 
                                        , columnType
                                        , header
                                        , field
                                        , nameField
                                        , valueField
                                        , nameFrontEndDictionaryToUse
                                        , fullDictionaryModelPathToLoad
                                        , editableEditMode
                                        , editableNewMode
                                        , showFillButton
                                        , fillGroupAttribute
                                        , sortOrder
                                        , showInEditMode
                                        , showInNewMode
                                        , showInNewSummaryMode
                                        , showInViewMode
                                        , showForExternal
                                        , requiredInNewMode
                                        , requiredInEditMode
                                        , patternToMatch
                                        , patternToMatchErrorMessage
                                        , width
                                        , minWidth
                                        , maxWidth
                                        )
VALUES ('HISEQ', 'Sample', 'text', 'Conc. (ng/uL)',      'concentration', NULL, NULL, NULL, NULL, 'Y', 'Y', 'Y', 'frontEndGridGroup', 100, 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', '^\d*(\.\d+)?$', 'Expects a decimal number', 7.5, 4, 9)
     , ('HISEQ', 'Sample', 'text', 'Volume (uL)',        'sampleVolume',  NULL, NULL, NULL, NULL, 'Y', 'Y', 'Y', 'frontEndGridGroup', 105, 'N', 'N', 'Y', 'Y', 'N', 'N', 'N', '^\d*(\.\d+)?$', 'Expects a decimal number', 7.5, 4, 9)
     , ('HISEQ', 'Sample', 'text', 'Volume (uL)',        'sampleVolume',  NULL, NULL, NULL, NULL, 'N', 'Y', 'Y', 'frontEndGridGroup', 105, 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', '^\d*(\.\d+)?$', 'Expects a decimal number', 7.5, 4, 9)
     , ('HISEQ', 'Sample', 'text', 'Sample Volume (uL)', 'sampleVolume',  NULL, NULL, NULL, NULL, 'N', 'N', 'N', 'frontEndGridGroup', 105, 'N', 'Y', 'N', 'N', 'N', 'N', 'N', '^\d*(\.\d+)?$', 'Expects a decimal number', 7.5, 4, 9);


INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory
                                        , gridType 
                                        , columnType
                                        , header
                                        , field
                                        , nameField
                                        , valueField
                                        , nameFrontEndDictionaryToUse
                                        , fullDictionaryModelPathToLoad
                                        , editableEditMode
                                        , editableNewMode
                                        , showFillButton
                                        , fillGroupAttribute
                                        , sortOrder
                                        , showInNewMode
                                        , showInNewSummaryMode
                                        , showInViewMode
                                        , showForExternal
                                        , showInEditMode
                                        , requiredInNewMode
                                        , requiredInEditMode
                                        , patternToMatch
                                        , patternToMatchErrorMessage
                                        , width
                                        , minWidth
                                        , maxWidth
                                        )
VALUES ('HISEQ', 'Sample', 'option', 'Sample Type',      'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes', NULL,  'Y', 'Y', 'Y', 'frontEndGridGroup', 201, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', '^\d*$', 'Expects a decimal number', 13, 9, NULL);

     
INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory
                                        , gridType 
                                        , columnType
                                        , header
                                        , field
                                        , nameField
                                        , valueField
                                        , nameFrontEndDictionaryToUse
                                        , fullDictionaryModelPathToLoad
                                        , editableEditMode
                                        , editableNewMode
                                        , showFillButton
                                        , fillGroupAttribute
                                        , sortOrder
                                        , showInNewMode
                                        , showInNewSummaryMode
                                        , showInViewMode
                                        , showForExternal
                                        , showInEditMode
                                        , requiredInNewMode
                                        , requiredInEditMode
                                        , patternToMatch
                                        , patternToMatchErrorMessage
                                        , width
                                        , minWidth
                                        , maxWidth
                                        )
VALUES ('HISEQ', 'Sample', 'option', 'Organism', 'idOrganism', 'display', 'idOrganism', NULL, 'hci.gnomex.model.OrganismLite',  'Y', 'Y', 'Y', 'frontEndGridGroup', 202, 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', '^\d*$', 'Unexpected error - please contact GNomEx Support', 13, 9, NULL);


INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'text-right', 'QC Conc. (ng/uL)', 'qualCalcConcentration', NULL,      NULL,       NULL,                        NULL,                          'Y',              'Y',             'Y',            'frontEndGridGroup', 203,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,             patternToMatchErrorMessage,                     width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'text-right', 'QC RIN',           'qualRINNumber',         NULL,      NULL,       NULL,                        NULL,                          'Y',              'Y',             'Y',            'frontEndGridGroup', 204,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)|([Nn]\/?[Aa])|(-)$', 'Expects a decimal number or N/A', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType, header,             field,              nameField, valueField,         nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'option',   'Seq Lib Protocol', 'idSeqLibProtocol', 'display', 'idSeqLibProtocol', 'seqLibProtocols',           NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 205,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*$',      'Unexpected error - please contact GNomEx Support', 20,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType, header,             field,           nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'text',     'Prepped by Core?', 'seqPrepByCore', NULL,      NULL,       NULL,                        NULL,                          'N',              'N',             'N',            'frontEndGridGroup', 206,       'N',           'N',                  'Y',            'N',             'N',            'N',               'N',                '^[YN]$',     NULL,                       5,     5,        NULL)


INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType, header,                 field,               nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'text',     'Actual Ave. Lib Size', 'meanLibSizeActual', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'N',            'frontEndGridGroup', 400,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,     8.5,    10)

INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType, header,                field,                  nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'text',     'QC Frag size (from)', 'qualFragmentSizeFrom', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 405,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)

INSERT INTO GNomEx.dbo.ColumnProperties ( codeRequestCategory, gridType , columnType, header,              field,                nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('HISEQ',              'Sample',  'text',     'QC Frag size (to)', 'qualFragmentSizeTo', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 410,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)


----------------------------------------------------------------------------------------------


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'text',     'Vol. (uL)',     'sampleVolume',  NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 105,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
                                                                                                                                                                                                                   

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 201,       'Y',           'Y',                  'Y',            'Y',             'Y',            'Y',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'option',   'Organism',      'idOrganism',    'display',    'idOrganism',   NULL,                        'hci.gnomex.model.OrganismLite', 'Y',              'Y',             'Y',            'frontEndGridGroup', 202,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^\d*$',           'Unexpected error - please contact GNomEx Support', 13,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'text-right', 'QC Conc. (ng/uL)', 'qualCalcConcentration', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 203,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,             patternToMatchErrorMessage,                     width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'text-right', 'QC RIN',           'qualRINNumber',         NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 204,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)|([Nn]\/?[Aa])|(-)$', 'Expects a decimal number or N/A', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,              nameField, valueField,         nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'option',   'Seq Lib Protocol', 'idSeqLibProtocol', 'display', 'idSeqLibProtocol', 'seqLibProtocols',           NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 205,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*$',      'Unexpected error - please contact GNomEx Support', 20,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,           nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample', 'text',     'Prepped by Core?', 'seqPrepByCore', NULL,      NULL,       NULL,                        NULL,                          'N',              'N',             'N',            'frontEndGridGroup', 206,       'N',           'N',                  'Y',            'N',             'N',            'N',               'N',                '^[YN]$',     NULL,                       5,     5,        NULL)


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                 field,               nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample',  'text',     'Actual Ave. Lib Size', 'meanLibSizeActual', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'N',            'frontEndGridGroup', 400,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,     8.5,    10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                field,                  nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample',  'text',     'QC Frag size (from)', 'qualFragmentSizeFrom', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 405,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,              field,                nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NOSEQ',             'Sample',  'text',     'QC Frag size (to)', 'qualFragmentSizeTo', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 410,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)


----------------------------------------------------------------------------------------------


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'text',     'Vol. (uL)',     'sampleVolume',  NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 105,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
                                                                                                                                                                                                                   

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 201,       'Y',           'Y',                  'Y',            'Y',             'Y',            'Y',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'option',   'Organism',      'idOrganism',    'display',    'idOrganism',   NULL,                        'hci.gnomex.model.OrganismLite', 'Y',              'Y',             'Y',            'frontEndGridGroup', 202,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^\d*$',           'Unexpected error - please contact GNomEx Support', 13,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'text-right', 'QC Conc. (ng/uL)', 'qualCalcConcentration', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 203,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,             patternToMatchErrorMessage,                     width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'text-right', 'QC RIN',           'qualRINNumber',         NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 204,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)|([Nn]\/?[Aa])|(-)$', 'Expects a decimal number or N/A', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,              nameField, valueField,         nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'option',   'Seq Lib Protocol', 'idSeqLibProtocol', 'display', 'idSeqLibProtocol', 'seqLibProtocols',           NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 205,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*$',      'Unexpected error - please contact GNomEx Support', 20,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,           nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample', 'text',     'Prepped by Core?', 'seqPrepByCore', NULL,      NULL,       NULL,                        NULL,                          'N',              'N',             'N',            'frontEndGridGroup', 206,       'N',           'N',                  'Y',            'N',             'N',            'N',               'N',                '^[YN]$',     NULL,                       5,     5,        NULL)


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                 field,               nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample',  'text',     'Actual Ave. Lib Size', 'meanLibSizeActual', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'N',            'frontEndGridGroup', 400,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,     8.5,    10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                field,                  nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample',  'text',     'QC Frag size (from)', 'qualFragmentSizeFrom', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 405,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,              field,                nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MISEQ',             'Sample',  'text',     'QC Frag size (to)', 'qualFragmentSizeTo', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 410,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)


----------------------------------------------------------------------------------------------


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,                    nameField,    valueField,              nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,        editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'option',   'Unit',          'codeConcentrationUnit',  'display',    'codeConcentrationUnit', NULL,                        'hci.gnomex.model.ConcentrationUnit', 'Y',              'N',             'Y',            'frontEndGridGroup', 105,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                NULL,           NULL,                       8.5,   8.5,      10)
                                                                                                                                                                                                                   

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,           nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text',     'Prepped by Core?', 'seqPrepByCore', NULL,      NULL,       NULL,                        NULL,                          'N',              'N',             'N',            'frontEndGridGroup', 200,       'N',           'N',                  'Y',            'N',             'N',            'N',               'N',                '^[YN]$',     NULL,                       5,     5,        NULL)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,                           field,                   nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text',     'Nucl. acid extraction method',   'otherSamplePrepMethod', NULL,         NULL,           'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 205,       'Y',           'N',                  'Y',            'Y',             'Y',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,  field,                     nameField, valueField,                nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'option',   'Assay', 'codeBioanalyzerChipType', 'display', 'codeBioanalyzerChipType', 'bioanalyzerChips',          NULL,                          'Y',              'Y',             'Y',            'frontEndGridGroup', 210,       'Y',           'Y',                  'Y',            'N',             'Y',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);
                                                                


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 202,       'Y',           'Y',                  'N',            'Y',             'Y',            'Y',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
       
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,                           field,                   nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text',     'Nucl. acid extraction method',   'otherSamplePrepMethod', NULL,         NULL,           'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 201,       'N',           'Y',                  'N',            'Y',             'N',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);
                                                                                                                                                                                                            
--INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage,                         width, minWidth, maxWidth)
--VALUES                                  ('QC',                'Sample', 'option',   'Organism',      'idOrganism',    'display',    'idOrganism',   NULL,                        'hci.gnomex.model.OrganismLite', 'Y',              'Y',             'Y',            'frontEndGridGroup', 215,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^\d*$',           'Unexpected error - please contact GNomEx Support', 13,    9,        NULL);
--
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text-right', 'QC Conc. (ng/uL)', 'qualCalcConcentration', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 220,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,       field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text-right', 'QC 260/230', 'qual260nmTo230nmRatio', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 223,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,             patternToMatchErrorMessage,                     width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample', 'text-right', 'QC RIN',           'qualRINNumber',         NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 225,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)|([Nn]\/?[Aa])|(-)$', 'Expects a decimal number or N/A', 9,    9,        NULL);

--INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,              nameField, valueField,         nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage,                         width, minWidth, maxWidth)
--VALUES                                  ('QC',                'Sample', 'option',   'Seq Lib Protocol', 'idSeqLibProtocol', 'display', 'idSeqLibProtocol', 'seqLibProtocols',           NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 230,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^\d*$',      'Unexpected error - please contact GNomEx Support', 20,    9,        NULL);
--
--
--INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                 field,               nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
--VALUES                                  ('QC',                'Sample',  'text',     'Actual Ave. Lib Size', 'meanLibSizeActual', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'N',            'frontEndGridGroup', 400,       'N',           'N',                  'Y',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,     8.5,    10)
--
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                field,                  nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample',  'text',     'QC Frag size (from)', 'qualFragmentSizeFrom', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 405,       'N',           'N',                  'N',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,              field,                nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('QC',                'Sample',  'text',     'QC Frag size (to)', 'qualFragmentSizeTo', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 410,       'N',           'N',                  'N',            'N',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)


----------------------------------------------------------------------------------------------


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'Y',           'Y',                  'Y',          'Y',               'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,                    nameField,    valueField,              nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,        editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'option',   'Unit',          'codeConcentrationUnit',  'display',    'codeConcentrationUnit', NULL,                        'hci.gnomex.model.ConcentrationUnit', 'Y',              'N',             'Y',            'frontEndGridGroup', 105,       'N',           'N',                  'Y',          'N',               'Y',            'N',               'N',                NULL,           NULL,                       8.5,   8.5,      10)
                                                                                                                                                                                                                   

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,             field,           nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showInEditMode, requiredInNewMode, showForExternal, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'text',     'Prepped by Core?', 'seqPrepByCore', NULL,      NULL,       NULL,                        NULL,                          'N',              'N',             'N',            'frontEndGridGroup', 200,       'N',           'N',                  'Y',            'N',            'N',             'N',               'N',                '^[YN]$',     NULL,                       5,     5,        NULL)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,                           field,                   nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'text',     'Nucl. acid extraction method',   'otherSamplePrepMethod', NULL,         NULL,           'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 205,       'Y',           'Y',                  'Y',          'Y',               'Y',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,  field,                     nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,          editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'option',   'Assay', 'codeBioanalyzerChipType', 'display', 'value',    NULL,                        'hci.gnomex.model.BioanalyzerChipType', 'Y',              'Y',             'Y',            'frontEndGridGroup', 210,       'Y',           'N',                  'Y',          'N',               'Y',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);
                                                                


INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 202,       'Y',           'N',                  'N',          'Y',               'Y',            'Y',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
           
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'N',              'N',             'N',            'frontEndGridGroup', 208,       'N',           'Y',                  'N',          'N',               'N',            'N',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'text-right', 'QC Conc. (ng/uL)', 'qualCalcConcentration', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 220,       'N',           'N',                  'Y',          'N',               'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,       field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'text-right', 'QC 260/230', 'qual260nmTo230nmRatio', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 223,       'N',           'N',                  'Y',          'N',               'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,             field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,             patternToMatchErrorMessage,                     width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'text-right', 'QC RIN',           'qualRINNumber',         NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 225,       'N',           'N',                  'Y',          'N',               'Y',            'N',               'N',                '^(\d*(\.\d+)?)|([Nn]\/?[Aa])|(-)$', 'Expects a decimal number or N/A', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,                field,                  nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample',  'text',     'QC Frag size (from)', 'qualFragmentSizeFrom', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 405,       'N',           'N',                  'N',          'N',               'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType , columnType, header,              field,                nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample',  'text',     'QC Frag size (to)', 'qualFragmentSizeTo', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 410,       'N',           'N',                  'N',          'N',               'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,      field,                     nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,          editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDSQ',              'Sample', 'option',   'Chip Type', 'codeBioanalyzerChipType', 'display', 'value',    NULL,                        'hci.gnomex.model.BioanalyzerChipType', 'Y',              'N',             'Y',            'frontEndGridGroup', 415,       'N',           'Y',                  'N',          'N',               'N',            'N',               'N',                NULL,           NULL,                       13,    9,        NULL);
                                                                

----------------------------------------------------------------------------------------------

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('ISOL',              'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'N',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)
   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType,   header,       field,                   nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad, editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,  patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('ISOL',              'Sample', 'text-right', 'QC 260/280', 'qual260nmTo280nmRatio', NULL,      NULL,       NULL,                        NULL,                          'Y',              'N',             'Y',            'frontEndGridGroup', 223,       'N',           'Y',                  'Y',          'N',               'Y',            'N',               'N',                '^\d*(\.\d+)?$', 'Expects a decimal number', 9,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,            nameField, valueField, nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('ISOL',              'Sample', 'option',   'Sample Source', 'idSampleSource', 'display', 'value',    NULL,                        'hci.gnomex.model.SampleSource', 'Y',              'Y',             'Y',            'frontEndGridGroup', 250,       'Y',           'Y',                  'N',            'Y',             'Y',            'Y',               'N',                '^\d*$',        'Unrecognized item',        13,    9,        NULL);
         
----------------------------------------------------------------------------------------------

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDMISEQ',           'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)                                                                                                                                                                

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDMISEQ',           'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 201,       'Y',           'Y',                  'Y',            'Y',             'Y',            'Y',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('MDMISEQ',           'Sample', 'option',   'Organism',      'idOrganism',    'display',    'idOrganism',   NULL,                        'hci.gnomex.model.OrganismLite', 'Y',              'Y',             'Y',            'frontEndGridGroup', 202,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^\d*$',           'Unexpected error - please contact GNomEx Support', 13,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,                           field,                   nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('MDMISEQ',           'Sample', 'text',     'Nucl. acid extraction method',   'otherSamplePrepMethod', NULL,         NULL,           'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 205,       'Y',           'N',                  'Y',            'Y',             'Y',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);

----------------------------------------------------------------------------------------------

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NANO',              'Sample', 'text',     'Conc. (ng/uL)', 'concentration', NULL,         NULL,           NULL,                        NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 100,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^(\d*(\.\d+)?)$', 'Expects a decimal number', 8.5,   8.5,      10)                                                                                                                                                                

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NANO',              'Sample', 'option',   'Sample Type',   'idSampleType',  'sampleType', 'idSampleType', 'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 201,       'Y',           'Y',                  'Y',            'Y',             'Y',            'Y',               'N',                '^\d*$',           'Expects a decimal number', 13,    9,        NULL);
                                                                                                                                                                                                                   
INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,          field,           nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch,    patternToMatchErrorMessage,                         width, minWidth, maxWidth)
VALUES                                  ('NANO',              'Sample', 'option',   'Organism',      'idOrganism',    'display',    'idOrganism',   NULL,                        'hci.gnomex.model.OrganismLite', 'Y',              'Y',             'Y',            'frontEndGridGroup', 202,       'Y',           'Y',                  'Y',            'Y',             'Y',            'N',               'N',                '^\d*$',           'Unexpected error - please contact GNomEx Support', 13,    9,        NULL);

INSERT INTO GNomEx.dbo.ColumnProperties (codeRequestCategory, gridType, columnType, header,                           field,                   nameField,    valueField,     nameFrontEndDictionaryToUse, fullDictionaryModelPathToLoad,   editableEditMode, editableNewMode, showFillButton, fillGroupAttribute,  sortOrder, showInNewMode, showInNewSummaryMode, showInViewMode, showForExternal, showInEditMode, requiredInNewMode, requiredInEditMode, patternToMatch, patternToMatchErrorMessage, width, minWidth, maxWidth)
VALUES                                  ('NANO',              'Sample', 'text',     'Nucl. acid extraction method',   'otherSamplePrepMethod', NULL,         NULL,           'sampleTypes',               NULL,                            'Y',              'Y',             'Y',            'frontEndGridGroup', 205,       'Y',           'N',                  'Y',            'Y',             'Y',            'Y',               'N',                NULL,           NULL,                       13,    9,        NULL);

----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

SELECT *
  FROM GNomEx.dbo.RequestCategory rc 
  JOIN GNomEx.dbo.ColumnProperties cp ON cp.codeRequestCategory = rc.codeRequestCategory









