buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id "com.github.node-gradle.node" version "3.1.1"
}

repositories {
    mavenCentral()
}

tasks.register('cleanAngular', NpmTask) {
    args = ['run', 'clean:dist']
}

tasks.register('cleanNpmInstall', NpmTask) {
    args = ['run', 'clean:install']
}

tasks.register('cleanAll', NpmTask) {
    args = ['run', 'clean']
}

tasks.register('buildWebpackDevWDS', NpmTask) {
    dependsOn(cleanAngular, npmInstall)
    args = ['run', 'build:dev:wds']
}

tasks.register('buildWebpackDevTomcat', NpmTask) {
    dependsOn(npmInstall)
    args = ['run', 'build:dev:tomcat']
}

tasks.register('buildWebpackProd', NpmTask) {
    dependsOn(cleanAngular, npmInstall)
    args = ['run', 'build:prod']
}

tasks.register('runWebpackDevServer', NpmTask) {
    args = ['run', 'webpack-dev-server']
}
