buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly group: 'org.apache.tomcat', name: 'tomcat-jdbc', version: '9.0.0.M10'
    compileOnly group: 'org.apache.tomcat', name: 'tomcat-catalina', version: '7.0.68'
    compileOnly group: 'log4j', name: 'log4j', version: '1.2.12'
    compileOnly project(':gnomex_crypt')
}

jar {
    manifest {
        attributes([
                'Built-By'              : 'u0974549',
                'Implementation-Version': '6.26.12'
        ], 'gnomex_tomcat_support')
    }
}
